// Automatically generated by astro-icon
// 4a4366be327933312c7b6d4a0b8b279ec2cf98d478b7571d21f78d546209645d

declare module 'virtual:astro-icon' {
	export type Icon =
		| 'fa6-solid:sun'
		| 'fa6-solid:moon'
		| 'fa6-solid:bars'
		| 'fa6-solid:xmark'
		| 'fa6-solid:backward-step'
		| 'fa6-solid:chevron-left'
		| 'fa6-solid:chevron-right'
		| 'fa6-solid:forward-step'
		| 'logos:github-icon'
		| 'logos:linkedin-icon'
		| 'logos:stackoverflow-icon'
		| 'logos:twitter'
		| 'logos:instagram-icon'
		| 'logos:lastfm';
}
